# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('department', models.CharField(choices=[('Приемное', 'Приемное'), ('Терапевтическое', 'Терапевтическое')], max_length=100)),
                ('attending_doctor', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=200)),
                ('ward', models.IntegerField()),
                ('destination', models.CharField(max_length=1000)),
            ],
        ),
    ]
